// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addToChripRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserToChirpRed = `-- name: AddUserToChirpRed :exec
UPDATE users SET is_chirp_red = TRUE WHERE id = $1
`

func (q *Queries) AddUserToChirpRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, addUserToChirpRed, id)
	return err
}
