// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoke_refresh_token.sql

package database

import (
	"context"
	"database/sql"
)

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET updated_at = $2, revoked_at = $2 WHERE token = $1
`

type RevokeTokenParams struct {
	Token     string
	UpdatedAt sql.NullTime
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.Token, arg.UpdatedAt)
	return err
}
