// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users SET email = $2, password = $3 WHERE id = $1 RETURNING id, created_at, updated_at, email, password
`

type UpdateUserInfoParams struct {
	ID       uuid.UUID
	Email    string
	Password string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.ID, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}
